### ISSUE TITLE
Python 3.8?

### ISSUE THREAD

**Issue by thwllms** [gyanz/pydsstools#10]
Are there any plans to make `pydsstools` compatible with Python 3.8 (for Windows)?

Thanks for creating this awesome library.

**Comment by gyanz** [comment]
I have updated library for Python 3.8. Please review changelog for additional information.

**Comment by thwllms** [comment]
Thanks so much! I couldn't pip install on 3.8.2, though, until I changed the `python_versions` string in `setup.py` to this:
```
    python_requires='>=3.6, <3.9',  # previously '>=3.6 <=3.8'
```

**Comment by gyanz** [comment]
I have corrected the setup file. Let me know if you experience other issues or have any suggestions.
