### ISSUE TITLE
Writing to a new DSS file

### ISSUE THREAD

**Issue by SercanC** [gyanz/pydsstools#12]
Hello,

I can successfully write to an existing DSS file. When I try to write to a new DSS file, the file is created successfully and it seems like some data is populated. When I try to open the DSS file with DSSVue, I get the "cannot access file" error.

Thanks for the package!
Sercan

**Comment by gyanz** [comment]
Hi Sercan,

The Open command takes the "version" argument. It can be either 6 or 7, and governs the file format of a new DSS file. Only the version 6 is compatible with the current DssVue software.

**Comment by SercanC** [comment]
Awesome, thank you!
