### ISSUE TITLE
ImportError: DLL load failed

### ISSUE THREAD

**Issue by SercanC** [gyanz/pydsstools#14]
I am having an having an ImportError after I updated the pydsstools package from an earlier version using Python 3.7. Do you have any ideas what the cause might be?

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/11078309/91479760-d06f2d80-e856-11ea-99cf-b67b55b608d3.png)

Best,
Sercan

**Comment by gyanz** [comment]
Starting version 1.6, pydsstools is dependent on Microsoft C++ Runtime libraries. I have provided link to download this in the Dependencies section of Readme.

**Comment by SercanC** [comment]
Thank you!
