### ISSUE TITLE
Cannot Access File

### ISSUE THREAD

**Issue by mohamedmorsy** [gyanz/pydsstools#15]
Every time I try to run Example 10 and after generating the example.dss, my HEC-DSSVue is not able to open it and I get the following message:

 Cannot Access File: filepath

**Comment by apreucil** [comment]
I had the same issue. I was able to open the file using HEC-DSSVue 3.0 or greater. Download that and it should fix your problem.

**Comment by mohamedmorsy** [comment]
@apreucil Thank you so much! I will give a try.

**Comment by skywalker788** [comment]
Facing the same issue. Hope that dss file produced will work with hec-hms. 
@apreucil Where did you found HEC-DSSVue 3.0? The last major version is 2.0 of Febrary 2010

**Comment by gyanz** [comment]
Following has download link for HEC-DSSVue 3.0: https://github.com/gyanz/pydsstools/blob/master/dssVue/DISCLAIMER.MD
