### ISSUE TITLE
Would Like to Compile pydsstools on Linux

### ISSUE THREAD

**Issue by brettpalmberg** [gyanz/pydsstools#17]
Good Afternoon.  How does one compile pydsstools?  Here is what I have tried so far:

The Dockerfile used to attempt a build is here: https://github.com/USACE/pydsstools/blob/feature/docker-linux-builds/Dockerfile .

Seeing the following:
![image](https://user-images.githubusercontent.com/29417036/101223462-bb721980-3651-11eb-937b-821e3770dcf2.png)

**Comment by ktarbet** [comment]
@gyanz  If you need header files included I'm happy to make a pull request.  Where would you like the DSS header files? Or other files?

**Comment by brettpalmberg** [comment]
@ktarbet @gyanz - have pydsstools building for x64/py38, but had to twiddle these lines to make it work without `DSSGrid_wrap.h`.  I'm not sure if this will cause underlying problems i'm not aware of:  
![image](https://user-images.githubusercontent.com/29417036/101375289-cfe22c00-3874-11eb-97ef-0243fc0d83a2.png)

**Comment by gyanz** [comment]
@brettpalmberg I have incorporated @ktarbet 's custom C++ code for reading DSS 6 grid. This code is not a part of HEC's DSS7 library. Your above edit will work fine as long as you don't read DSS 6 grid.

The function I need from Karl's code is C++ type, so I added few C type interface files for use in pydsstools. These files are in the link below. I can also email you Karl's code and my modification together.
[DSSGrid.zip](https://github.com/gyanz/pydsstools/files/5655222/DSSGrid.zip)

**Comment by gyanz** [comment]
I use the following to build the library in my machine. 

```
cython -3 ../core_heclib.pyx -o $ext_c_file
gcc -v -Wall -Wl,--warn-once -m64 -g -shared -fPIC $ext_c_file -I"$PY_INCL" -I"$DSS7_INCL" -I"$PY_NPY_INCL" -I"$DSS6_INCL" -L"$PY_LIB" -L"$DSS7_LIB" -L"$DSS6_LIB" -l:heclib.a -l:grid.a -lgfortran -lpthread -lm -lquadmath -lz -lstdc++ -o "$ext_module"
```
