### ISSUE TITLE
Support Python 3.6.11 ?

### ISSUE THREAD

**Issue by meteorolog90** [gyanz/pydsstools#19]
pip install https://github.com/gyanz/pydsstools/zipball/master
Collecting https://github.com/gyanz/pydsstools/zipball/master
  Using cached https://github.com/gyanz/pydsstools/zipball/master
Requirement already satisfied: numpy>=1.16.4 in ./env/lib/python3.6/site-packages (from pydsstools==1.6) (1.18.5)
Requirement already satisfied: pandas in ./env/lib/python3.6/site-packages (from pydsstools==1.6) (1.0.4)
Collecting affine
  Downloading affine-2.3.0-py2.py3-none-any.whl (15 kB)
ERROR: Package 'pydsstools' requires a different Python: 3.6.11 not in '~=3.8'

**Comment by gyanz** [comment]
It looks like you are using Linux. You need Python 3.8 to use pydsstools in Linux.

**Comment by meteorolog90** [comment]
Yes Linux. I posted error from server machine, on which it is Python 3.6. Then i tested on Ubuntu 20.04LTS, which have Python 3.8 and it works. But i'm sad, because need **pydsstools** for this server machine.

Anyway, thank you for answer

**Comment by gyanz** [comment]
Hi, it is just impractical for me to provide compiled binaries for multiple Python versions and operating systems. I have recently started working on a new version that will allow users to compile the library themselves. You can use this version in your server machine. I estimate to release this by end of February.

**Comment by meteorolog90** [comment]
> Hi, it is just impractical for me to provide compiled binaries for multiple Python versions and operating systems. I have recently started working on a new version that will allow users to compile the library themselves. You can use this version in your server machine. I estimate to release this by end of February.

Great, thank you. I will follow this updates

**Comment by MikeNeilson** [comment]
@gyanz, the github action system has really good support for matrix builds, which makes repeating operations using different versions pretty easy, that I've used for other projects. Other than just the time to set it up is there anything stopping the project using the github feature to generate the the library and run tests?

By way of example I set this up today for another python project: https://github.com/MikeNeilson/repgen5/blob/main/.github/workflows/tests.yml

**Comment by MikeNeilson** [comment]
Though as a more concrete example for this project I just took the liberty of creating a simple version of this idea. The results are... mixed.
https://github.com/MikeNeilson/pydsstools/actions/runs/563008000

3.7 and 3.8 ran `python setup.py install` just fine on ubuntu-18.04 and windows, 3.5 and 3.6 had errors with the supporting libraries like numpy and pandas. So depending on whether that's an issue with those libraries may not be worth your time.

If you like this let me know and I'll submit a pull request.

**Comment by gyanz** [comment]
@MikeNeilson thanks for your effort and suggestions. I will look into github action system, which I am not familiar with.

Anyways, python extension module in Windows has runtime dependency on the specific version of python. For example, module compiled with Python 3.7.x is linked with python37.dll. This python version dependency does not exist in Linux, however, as shown in the core_heclib.so information below, there are other libraries that must be satisfied (e.g., lib.so.6) and compatible with python libraries.

![image](https://user-images.githubusercontent.com/27383270/108016971-01901580-6fd1-11eb-85b3-245a12c2240b.png)

**Comment by gyanz** [comment]
@meteorolog90 I have uploaded the new version. Please follow the updated instruction to install from source.

**Comment by majosgithub** [comment]
@gyanz will it work in python 3.11.2 ?
