### ISSUE TITLE
example3.py ModuleNotFoundError: No module named 'pydsstools.core.core_heclib'

### ISSUE THREAD

**Issue by danhamill** [gyanz/pydsstools#2]
Hi,

Thanks for the great package.  

I installed using:

```
pip install https://github.com/gyanz/pydsstools/zipball/master
```

Which seemed to work fine.  After trying a few of the example scripts, I got the following error when I ran example3.py.

```python
python example3.py
Traceback (most recent call last):
  File "example3.py", line 7, in <module>
    from pydsstools.heclib.utils import HecTime
  File "C:\Anaconda3\lib\site-packages\pydsstools\heclib\utils.py", line 1, in <module>
    from ..core.core_heclib import (HecTime, DssStatusException, GranularityException,ArgumentException)
ModuleNotFoundError: No module named 'pydsstools.core.core_heclib'
```

A bit about my computer:
```
windows 10            10.0.17134
python                    3.7.1                h33f27b4_4
pandas                    0.24.2                   pypi_0    pypi
numpy                     1.16.2                   pypi_0    pypi
cython                    0.29.6           py37ha925a31_0
```

I looked in `_Lib` and only found the .pyd file.  Do you have the cython files I could look at?  If so, I can submit PR.

Thanks!

Dan

**Comment by gyanz** [comment]
Hi Dan,

This is a bug. The core package does not have core_heclib subpackage. This can be fixed by modifying import statement in utils.py as follows:
`from ..core import (HecTime, DssStatusException, GranularityException,ArgumentException)`

and appending above imports in __all__ variable of core package. You are welcome to make these changes and submit the PR.

**Comment by gyanz** [comment]
I made the correction. Example 3 ran without import error.

**Comment by danhamill** [comment]
Thank you.  Same result over here!
