### ISSUE TITLE
Question about SHG grid to tiff

### ISSUE THREAD

**Issue by gyanz** [gyanz/pydsstools#21]
I used pydsstools to generate tiff from grid data in the attached dss file. The following figure shows this tiff layer in QGIS with background map. Based on the source of data, I had expected the tiff to be on top of Texas. Can someone please confirm the tiff was generated correctly based on the grid's meta data? @brettpalmberg @jeffsuperglide @MikeNeilson @ktarbet @danhamill @eheisman

![SHG_pydsstools](https://user-images.githubusercontent.com/27383270/113071646-0d4b2c00-917a-11eb-9f67-0c539aa5c2e5.PNG)
[data.zip](https://github.com/gyanz/pydsstools/files/6233016/data.zip)

**Comment by apreucil** [comment]
Hi Gyanz, I put the tif into ArcGIS pro and got the same image you did. I checked the map projection and it is the same as the projection information listed in the DSS (see first 3 images below). 

For what its worth, I pulled the precipitation on Jan 30, 2020 from the AHPS precip analysis (see last image) and it does look a bit different than the tifs. Perhaps there was an issue with the initial data download/conversion to dss?

![Capture](https://user-images.githubusercontent.com/60394347/113159991-10422d00-920b-11eb-9b0f-3fa661cf680a.PNG)
![Capture2](https://user-images.githubusercontent.com/60394347/113160022-1801d180-920b-11eb-9aba-ef089343df7e.PNG)
![Capture3](https://user-images.githubusercontent.com/60394347/113160073-23ed9380-920b-11eb-9b6c-027c65ca6787.PNG)
![image](https://user-images.githubusercontent.com/60394347/113161047-040a9f80-920c-11eb-8df6-8caec7ade757.png)

**Comment by danhamill** [comment]
@gyanz I think there is something wrong with your geotransform.  The tiff your provided has:

```
Upper Left  (       0.000, 1690000.000) ( 96d 0' 0.00"W, 38d14'32.83"N)
Lower Left  (   0.0000000,   0.0000000) ( 96d 0' 0.00"W, 23d 0' 0.00"N)
Upper Right ( 1820000.000, 1690000.000) ( 75d20'19.53"W, 36d28'11.84"N)
Lower Right ( 1820000.000,       0.000) ( 78d46'17.14"W, 21d28'23.87"N)
Center      (  910000.000,  845000.000) ( 86d30'41.51"W, 30d16'18.07"N)
```
Which would result in this affine transformation:

```
Affine(2000.0, 0.0, 0.0000000,
       0.0, -2000.0, 1690000.000)
```

The raster output raster should have:

```
Corner Coordinates:
Upper Left  (-1326000.000, 1800000.000) (111d21'59.64"W, 38d15'55.08"N)
Lower Left  (-1326000.000,  110000.000) (108d45'23.76"W, 23d11'31.11"N)
Upper Right (  494000.000, 1800000.000) ( 90d13'54.74"W, 39d 5'24.19"N)
Lower Right (  494000.000,  110000.000) ( 91d13'22.14"W, 23d53'47.35"N)
Center      ( -416000.000,  955000.000) (100d24' 8.11"W, 31d34'59.62"N)
```

You would want this for the geotransorm:

```
Affine(2000.0, 0.0, -1326000.0,
       0.0, -2000.0, 1800000.0)
#Affine(2000.0, 0.0, Lower_left_x*cell_resolution,
#       0.0, -2000.0, Lower_left_Y*cell_resolution + nrows*2000)
````

![image](https://user-images.githubusercontent.com/11522898/113168161-6797cb80-9212-11eb-8c51-865235e85db2.png)

**Comment by gyanz** [comment]
The grid and tiff both have transform as Affine(cell_width, 0, xmin, 0, -cell_height, ymax). The (xmin, ymax) is the coordinates of the top left corner of the top left cell. I think this is correct formulation for the transform. The (xmin, ymax) was calculated based on the origin coordinates or the (XCoord, YCoord) of Grid Cell Zero. I am starting to think either the origin coordinates is incorrect or I am interpreting it incorrectly.

**Comment by danhamill** [comment]
Which zero?

![image](https://user-images.githubusercontent.com/11522898/113291046-7046db00-92c0-11eb-8fa0-d6b814ee760d.png)

**Comment by gyanz** [comment]
I am referring to the first figure. My understanding is that the origin coordinates of the "raster" can be anything including (0,0). And that the origin of the spatial reference system is at 0 lat and -96 long for Albers coordinate reference system.

**Comment by danhamill** [comment]
The xy coords of the lower left corner of the raster are defined in the detailed grid info

lower left x = -63*2000 meters
lower left y = 55 * 2000 meters

The xy coords of the upper left corner would be

upper left  x = -63 * 2000 meters = -1326000.000 meters
upper left y = 55* 2000 + 845 * 2000 meters = 1800000.000 = meters

Where 845 is the number of rows.   The xy coordinate 0 meters, 0 meters is shown below as the red cross.:

![image](https://user-images.githubusercontent.com/11522898/113322526-cb89c500-92e2-11eb-9ce7-de129c908417.png)

**Comment by gyanz** [comment]
@danhamill Thanks for the clarification. According to your calculation, the Grid Cell Zero is located at origin of Albers crs. This means I was calculating the transform value incorrectly.

**Comment by danhamill** [comment]
Here is a plot showing the upper left corner of the raster and the image values greater than zero.  The upper left corner is in southern central Utah.

![image](https://user-images.githubusercontent.com/11522898/113326523-c8450800-92e7-11eb-8263-523ee8c3db89.png)

**Comment by gyanz** [comment]
Thanks @danhamill and @apreucil. I have revised the source code. I will keep this issue open to get additional comments.
