### ISSUE TITLE
Problems with the installation of the library

### ISSUE THREAD

**Issue by sumitsaini326** [gyanz/pydsstools#27]
![image](https://user-images.githubusercontent.com/39621731/129538816-cecd174a-079d-4367-9f49-928e8bbdc5d6.png)
![image](https://user-images.githubusercontent.com/39621731/129538873-d73f4c96-bf66-4561-bed1-fbf043e5aeea.png)

**Comment by gyanz** [comment]
@sumitsaini326 It looks like you don't have Fortran Compiler installed. Please read the build environment requirements in "Build from sources" of README.
