### ISSUE TITLE
Required DSS-6 format instead of DSS-7

### ISSUE THREAD

**Issue by nikhilteja91** [gyanz/pydsstools#28]
Hi. I want to write all the grids to DSS-6 version only instead of DSS-7. What can I do (edit) in the script so that all my files are in DSS-6 version only? Please help me out. Because, the DSS-7 version files are unable to run in HEC-HMS 4.6.1. Coule you please tell me any alternative? 

Thanks

**Comment by gyanz** [comment]
Writing grid data to DSS-6 version is not supported by this library.

**Comment by nikhilteja91** [comment]
Could you please tell me any alternate way to write data to DSS-6 version. Any assistance you can provide would be greatly appreciated, as it will be helpful for my research.

**Comment by gyanz** [comment]
Sorry, I don't have information about the alternate method.
