### ISSUE TITLE
Written dss file not valid in HEC HMS

### ISSUE THREAD

**Issue by steezbert** [gyanz/pydsstools#31]
Hey Gyan,

I am currently working on a project with HEC HMS and HEC RAS and your package has been a big help getting all the data into dss files. Unfortunately I am getting an error if I try to use the dss file of gridded precipitation in HEC HMS. I can open and view the dss file containing my grids in dssvue and it says the record has no issues.

![dssvue](https://user-images.githubusercontent.com/35223372/142857085-a39a7dc0-bb11-44e2-8576-bb56a2d9e145.png)

But when I try to use them in HEC HMS (4.8) I get the following error mesage:

![HEC_HMS_ERROR_3](https://user-images.githubusercontent.com/35223372/142847909-82ee1fbb-9648-426e-bb77-bec993b7c369.png)

As the beta version of HEC HMS (4.9) has a grid validation check tool I tried opening the file with that version to get some more information. What I did get is those two additional error messages:

![HEC_HMS_ERROR_1](https://user-images.githubusercontent.com/35223372/142848273-19730f6e-b3a4-4dac-9bac-f28c64b3de44.png)

![HEC_HMS_ERROR_2](https://user-images.githubusercontent.com/35223372/142848276-f4b17450-e1ad-4542-b470-b293e5e56a87.png)

I was wondering if this is a known Issue (I could not find anything listed) and if there is a way to fix it. 

This is a shortened version of the code I am using to write my precipitation data from a geotiff stack into the dss file:

`

    from os import path
    import pandas as pd
    import rasterio
    from affine import Affine
    from pydsstools.heclib.dss.HecDss import Open
    from pydsstools.heclib.utils import gridInfo
    
    radolan_file_path = r'C:\FILEPATH\Sachsen_Kemnitz_200107.tif'
    
    dss_file = r"C:\FILEPATH\RADOLAN_example.dss"
    
    
    #load monthly RADOLAN raster stack
    raster_stack = rasterio.open(radolan_file_path)
    
    #loop over raster layers
    #for j in range(1, (raster_stack.count)+1):
    for i in range(0, 3):
      
        layers = [63, 64, 65]
        layer = layers[i]
        
        #get single raster layer
        raster = raster_stack.read(layer, masked=False)
        
        pathnames = ["/UTM33N/SACHSEN_KEMNITZ/PRECIP/02JUL2017:0505/01JUL2017:0510/RADOLAN/",
        "/UTM33N/SACHSEN_KEMNITZ/PRECIP/02JUL2017:0510/01JUL2017:0515/RADOLAN/",
        "/UTM33N/SACHSEN_KEMNITZ/PRECIP/02JUL2017:0515/01JUL2017:0520/RADOLAN/"]
        
        pathname_out = pathnames[i]
        
        #open dss file
        with Open(dss_file) as dss_con:
            
            #prepare data to be put into dss file
            data = raster
            grid_info = gridInfo()
            cellsize = 1000
            xmin = raster_stack.bounds.left
            ymin= raster_stack.bounds.bottom
            ymax = raster_stack.bounds.top
            affine_transform = Affine(cellsize,0,xmin,0,-cellsize,ymax)
            grid_info.update([('grid_type', 'specified'),
                              ('grid_crs', 'EPSG:25833'),
                              ('grid_transform', affine_transform),
                              ('data_type', 'per-cum'),
                              ('data_units', 'mm'),
                              ('opt_crs_name', 'UTM33N'),
                              ('opt_crs_type', 0)])
            
            #put data in dss file
            dss_con.put_grid(pathname_out, data, grid_info)
`

I also want to mention, that I have the same issue using your example code to write grid data into a dss file, however the example files you provide seem to work.

This is the virtual environment I am using:

affine          2.3.0
attrs           21.2.0
certifi         2021.10.8
click           8.0.3
click-plugins   1.1.1
cligj           0.7.2
colorama        0.4.4
cycler          0.11.0
Cython          0.29.24
GDAL            3.3.2
kiwisolver      1.3.2
matplotlib      3.4.3
numpy           1.21.3
pandas          1.3.4
Pillow          8.4.0
pip             20.2.3
pydsstools      2.1
pyparsing       3.0.4
python-dateutil 2.8.2
pytz            2021.3
rasterio        1.2.10
regex           2021.11.2
setuptools      49.2.1
six             1.16.0
snuggs          1.4.7

I testet this on two different computers under Windows 10 and independent installations.

I am thankfull for any help.

Best Regards
Siggi

**Comment by gyanz** [comment]
@steezbert You may be using grid or coordinate system that is not compatible with HEC-HMS. Sorry, I don't have expertise in HEC-HMS to resolve this issue.

**Comment by steezbert** [comment]
Hey @gyanz,
thank you for your quick answer. I am using UTM33N which should work with HEC-HMS. 
As mentioned I have the same issue using your example code to write gridded data into a dss file.
I also tried using SHG and Albers as a reference system but the issue is the same.
Do you have any idea what could go wrong while writing into the dss file as it seems to be an issue with the file name or pointer?

**Comment by danhamill** [comment]
Just looking though the OP I think your grids are not properly georeferenced.  The lower cell should not be (0,0). Why aren't you using xmin and ymin to construct the affine?

Better yet, why not use raster_stack.transform to get the affine transformation from the source grids?

**Comment by steezbert** [comment]
Thank you @danhamill  for your input. You are right in my case the lower left cell should not be (0,0). Looks like I took the screenshot from a bad example. But that should not be the issue, as I tried different settings for the lower left indexing.

I did also transfrom on the raster stack and single raster and used pydsstools lower_left_xy_from_transform (which it uses internally as well I think) to get the lower left cell for the grid index. Using xmin and ymax from the bounding box should be the same as getting the values from the affine, as both describes the corners of the raster (I checked that of course, for the raster and the resulting dss file. It is the same).

I am using xmin and ymax from the bounding box for another reason and this might be interesting for you too @gyanz. As I am not 100% sure if I am right I did not mention it befor and I thought it would not matter or I could work around it. I think pydsstools calculates a wrong lower left for the grid in the dss file as it uses affine and xmin, ymax which is the upper left corner and not the lower left corner of the grid. Here is a screenshot from the code from https://github.com/gyanz/pydsstools/blob/master/pydsstools/src/grid.pyx :

![lower_left_pydsstools](https://user-images.githubusercontent.com/35223372/143452508-f5229cb8-535d-46f0-b0b8-543708b3de97.png)

On DSS Programmers Guide for Java (https://www.hec.usace.army.mil/confluence/dssjavaprogrammer/dss-progammers-guide-for-java/appendix-c-grid-classes-in-hec-java-programs/extent-functions) I found that the lower left corner of the grid is calculatet from xmin,ymin, which is the lower left corner of the raster as well:

![lower_left_java](https://user-images.githubusercontent.com/35223372/143452866-b52a4997-3efa-488a-afff-d3fc9cd1a7bf.png)

So what I did is caclulate the lower left for the grid in the dss file from the xmin and ymin from the bounding box. To see the effects of that I loaded the original raster data from the geotiff and the retrieved rasters from the written dss files into Qgis:

![qgis1](https://user-images.githubusercontent.com/35223372/143453544-13bb0198-5c53-4b98-95ff-a97280cbeddf.png)

As you can see, when using xmin and ymin my retrieved raster matches the original pretty good. (The slight offset comes from the rounding which is needed for the dss file, also I used rounding and not floor to minimize the offset, of course I tested both)
When using pydsstools lower_left_xy_from_transform (which think it is used internally, as the values match the root error warning you get when you don't use the 'opt_lower_left_x' and 'opt_lower_left' option in the grid_info) the offset is way bigger to the north, which makes sense, as it uses the rasters upper left corner as the grid lower left in the dss file.

For that reason I think you can tell that this sould not be the reason why the dss data is not working in HEC-HMS, as I am able to write my raster data from geotiff to dss, view it in dssvue and retrieve the data back to geotiff.

Sorry for the long text, I just wanted to present my problem in detail and show that I thought about where the probleme may come from. I am still looking to solve the problem. I thought using 'grid_type' == 'specified-time' could help, but when I use it i get the following error:

"Exception: For %s grid type, DPart and EPart of pathname must be datetime string" 

which may be related to the problem mentioned by @jeffsuperglide in issue #29.

Any help is still welcome!

**Comment by gyanz** [comment]
@steezbert Since you are able to open the grid record in HEC-DSSVue, there is nothing wrong with the grid data itself. There is however possibility of Garbage In, Garbage Out scenario with inappropriate grid meta data. For example, you can create SHG grid located outside North America using this library. Nevertheless, the "zopen" error message you have posted may be related to dss file and grid versions. Please verify that HEC-HMS supports HEC-DSS 7.

**Comment by steezbert** [comment]
I could not reply earlier, so sorry for that. I did some testing today and it seems like HEC-HMS does not support dss version 7 files. Hope they implement it soon as pydsstools makes data entry so much easier. Back to batching HEC-Vortex it is for now.
Thanks all for your help.

**Comment by danhamill** [comment]
@steezbert Good idea!  Just make sure you handle the nodata values correctly.  Vortex expects NaN for no-data, so you might have to sanitize if you need to rerpoject/resample your grids
