### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by AlJoz** [gyanz/pydsstools#37]
Hi, I try to install the repository using pip install https://github.com/gyanz/pydsstools/zipball/master command on my PC but I get the below error. 
Could you please provide any advice on the above? It would be much appreciated.
Thanks,

pip install https://github.com/gyanz/pydsstools/zipball/master

Collecting https://github.com/gyanz/pydsstools/zipball/master
  Using cached https://github.com/gyanz/pydsstools/zipball/master
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting affine
  Using cached affine-2.3.0-py2.py3-none-any.whl (15 kB)
Requirement already satisfied: numpy>=1.16.4 in c:\programdata\anaconda3\lib\site-packages (from pydsstools==2.2) (1.20.1)
Requirement already satisfied: pandas in c:\programdata\anaconda3\lib\site-packages (from pydsstools==2.2) (1.2.4)
Requirement already satisfied: pytz>=2017.3 in c:\programdata\anaconda3\lib\site-packages (from pandas->pydsstools==2.2) (2021.1)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\programdata\anaconda3\lib\site-packages (from pandas->pydsstools==2.2) (2.8.1)
Requirement already satisfied: six>=1.5 in c:\programdata\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas->pydsstools==2.2) (1.15.0)
Building wheels for collected packages: pydsstools
  Building wheel for pydsstools (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' 'C:\ProgramData\Anaconda3\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\axj0964\AppData\Local\Temp\tmp8vyau6sc'
       cwd: C:\Users\axj0964\AppData\Local\Temp\pip-req-build-0n0uifjx

**Comment by gyanz** [comment]
I suggest you to install using the second approach in README: Installation from binary wheels. The approach you are currently using requires you to have various compilers installed on your machine.

**Comment by AlJoz** [comment]
Thank you @gyanz . It is working now.
