### ISSUE TITLE
Feature Request: Squeeze

### ISSUE THREAD

**Issue by danhamill** [gyanz/pydsstools#4]
I would be very nice to have the squeeze functionality added to this package.  

Do you have any insight into how complicated this might be?

**Comment by gyanz** [comment]
This is easy. I will make the squeeze function available in the next update.

**Comment by danhamill** [comment]
Famous last words 🕵🏻‍♂️

Thanks!

**Comment by gyanz** [comment]
You can use dss squeeze as follows:
```
from pydsstools.heclib.utils import squeeze_file
squeeze_file(dss_file_path)
```

**Comment by danhamill** [comment]
Sweet!
