### ISSUE TITLE
Support for python 3.11

### ISSUE THREAD

**Issue by scottRMA** [gyanz/pydsstools#42]
Will there be any planned updates for python 3.11? The new update has some great speed increases I'd like to use this library with.

thank you!

**Comment by gyanz** [comment]
Yes. I am currently retooling the grid data interface. Once this is complete, I will release binaries for 3.11 and older python versions.

**Comment by openSourcerer9000** [comment]
1 vote for 3.10 here, this is the last lib we're waiting on to make the jump

**Comment by gyanz** [comment]
The latest update provides wheels for python 3.11.
