### ISSUE TITLE
Unable to install in windows 11 pro getting error wheel is not supported

### ISSUE THREAD

**Issue by majoanto** [gyanz/pydsstools#49]
Dear Gyanz, 
I am trying to install pydsstools library in windows 11 pro edition with python 3.11, but getting error like the wheel file is not supported. Could you please update the wheel file so that it gets supported  in windows 11 pro too.

**Comment by gyanz** [comment]
Theoretically, the pydsstools wheel available in PyPI should work with Windows 11. However, I don't have Windows 11 to confirm this.

**Comment by majoanto** [comment]
I got the above error in windows 11 tried multiple times, when you are upgrading to Windows 11 , Kindly check and reply.

**Comment by gyanz** [comment]
The latest wheels available in (PyPi) were built and tested in Windows 11. Please post the screenshot of command you used to install pydsstools and the corresponding error messages.
