### ISSUE TITLE
print statements

### ISSUE THREAD

**Issue by mxkpp** [gyanz/pydsstools#52]
Most of the library uses logging calls, but there are some lingering print statements that produce a lot of output with no way to suppress them without changing core code in a fork.  Notably this one that executes for every grid record written.

https://github.com/gyanz/pydsstools/blob/d65443b49adc6afb2a623afa19e2d5413f8cb6e7/pydsstools/heclib/dss/HecDss.py#L445

**Comment by gyanz** [comment]
I will fix this, thanks.

**Comment by gyanz** [comment]
This issue has been addressed in 2.3.2.

**Comment by mxkpp** [comment]
Thank you! Soon I want to upgrade to the latest then I could work on PRs for some things.
