### ISSUE TITLE
Regular Interval Time Series Data - Missing Values

### ISSUE THREAD

**Issue by mylesmcm** [gyanz/pydsstools#8]
If data is missing in a DSS record, DSS returns the max negative float value = -3.4028235e+38

This is by design, so the user must handle any values equal to the max negative float. Otherwise, any missing values will be erroneously displayed in the user's tables and plots as -3.4028235e+38. Example shown below.

![image](https://user-images.githubusercontent.com/51373333/68435638-a6863680-0170-11ea-82b7-db5dda98e336.png)

![image](https://user-images.githubusercontent.com/51373333/68435661-b56ce900-0170-11ea-87d7-6ec013d247b6.png)

**Comment by gyanz** [comment]
@mylesmcm timeseries object has nodata attribute, which is Boolean numpy array containing True value for each missing element. Internally, it uses zisMissingFloat/zisMissingDouble functions that handle both DSS 6 and 7 missing values.

**Comment by mylesmcm** [comment]
Thank you @gyanz . I used the nodata attribute as a column in a dataframe and then the numpy method: where() to modify the 'Values' column with a conditional on the nodata - 'Missing' column.  The conditional is: If 'Missing' is True then set Value to NaN. 

By setting any missing value to NaN, instead of the sentinal value of -3.4028235e+38 for DSS version 7 files, other Python libraries that work with Pandas and Numpy data will use the NaN values correctly.

FYI, DSS version 6 files will have a sentinal value of -901.00 for missing values.

An Example, using the same dataset from my original post, with missing data now accounted for, is shown below:


<pre style="color:#000000;background:#f1f0f0;"><span style="color:#400000; font-weight:bold; ">import</span> plotly
<span style="color:#400000; font-weight:bold; ">from</span> plotly<span style="color:#806030; ">.</span>graph_objs <span style="color:#400000; font-weight:bold; ">import</span> Scatter<span style="color:#806030; ">,</span> Layout
<span style="color:#400000; font-weight:bold; ">from</span> pydsstools<span style="color:#806030; ">.</span>heclib<span style="color:#806030; ">.</span>dss <span style="color:#400000; font-weight:bold; ">import</span> HecDss
<span style="color:#400000; font-weight:bold; ">import</span> numpy <span style="color:#400000; font-weight:bold; ">as</span> np
<span style="color:#400000; font-weight:bold; ">import</span> pandas <span style="color:#400000; font-weight:bold; ">as</span> pd

dss_file <span style="color:#806030; ">=</span> <span style="color:#e60000; ">"example.dss"</span>
pathname <span style="color:#806030; ">=</span> <span style="color:#e60000; ">"/REGULAR/TIMESERIES/FLOW//1HOUR/Ex1/"</span>
startDate <span style="color:#806030; ">=</span> <span style="color:#e60000; ">"15JUL2019 19:00:00"</span>
endDate <span style="color:#806030; ">=</span> <span style="color:#e60000; ">"15JUL2019 23:00:00"</span>

fid <span style="color:#806030; ">=</span> HecDss<span style="color:#806030; ">.</span><span style="color:#800000; font-weight:bold; ">Open</span><span style="color:#806030; ">(</span>dss_file<span style="color:#806030; ">)</span>
ts <span style="color:#806030; ">=</span> fid<span style="color:#806030; ">.</span>read_ts<span style="color:#806030; ">(</span>pathname<span style="color:#806030; ">,</span>window<span style="color:#806030; ">=</span><span style="color:#806030; ">(</span>startDate<span style="color:#806030; ">,</span>endDate<span style="color:#806030; ">)</span><span style="color:#806030; ">,</span>trim_missing<span style="color:#806030; ">=</span><span style="color:#074726; ">True</span><span style="color:#806030; ">)</span>

df <span style="color:#806030; ">=</span> pd<span style="color:#806030; ">.</span>DataFrame<span style="color:#806030; ">(</span><span style="color:#806030; ">)</span>
df<span style="color:#806030; ">[</span><span style="color:#e60000; ">'Times'</span><span style="color:#806030; ">]</span> <span style="color:#806030; ">=</span> ts<span style="color:#806030; ">.</span>pytimes
df<span style="color:#806030; ">[</span><span style="color:#e60000; ">'Values'</span><span style="color:#806030; ">]</span> <span style="color:#806030; ">=</span> ts<span style="color:#806030; ">.</span>values
df<span style="color:#806030; ">[</span><span style="color:#e60000; ">'Missing'</span><span style="color:#806030; ">]</span> <span style="color:#806030; ">=</span> ts<span style="color:#806030; ">.</span>nodata
df<span style="color:#806030; ">.</span>Values <span style="color:#806030; ">=</span> np<span style="color:#806030; ">.</span>where<span style="color:#806030; ">(</span>df<span style="color:#806030; ">.</span>Missing <span style="color:#44aadd; ">==</span> <span style="color:#074726; ">True</span><span style="color:#806030; ">,</span> np<span style="color:#806030; ">.</span>NaN<span style="color:#806030; ">,</span> df<span style="color:#806030; ">.</span>Values<span style="color:#806030; ">)</span>

<span style="color:#400000; font-weight:bold; ">print</span> <span style="color:#806030; ">(</span>df<span style="color:#806030; ">)</span>

fid<span style="color:#806030; ">.</span>close<span style="color:#806030; ">(</span><span style="color:#806030; ">)</span>

plotly<span style="color:#806030; ">.</span>offline<span style="color:#806030; ">.</span>plot<span style="color:#806030; ">(</span><span style="color:#806030; ">{</span>
    <span style="color:#e60000; ">"data"</span><span style="color:#806030; ">:</span> <span style="color:#806030; ">[</span>Scatter<span style="color:#806030; ">(</span>x<span style="color:#806030; ">=</span>df<span style="color:#806030; ">.</span>Times<span style="color:#806030; ">,</span> y<span style="color:#806030; ">=</span>df<span style="color:#806030; ">.</span>Values<span style="color:#806030; ">)</span><span style="color:#806030; ">]</span><span style="color:#806030; ">,</span>
    <span style="color:#e60000; ">"layout"</span><span style="color:#806030; ">:</span> Layout<span style="color:#806030; ">(</span>title<span style="color:#806030; ">=</span><span style="color:#e60000; ">"hello world"</span><span style="color:#806030; ">)</span>
<span style="color:#806030; ">}</span><span style="color:#806030; ">)</span>
</pre>


![image](https://user-images.githubusercontent.com/51373333/68790002-5c330880-05fb-11ea-93b5-5db1fe2d6b00.png)

If there are better known ways to handle the missing data, please share.

**Comment by gyanz** [comment]
@mylesmcm I use the following approach:
```
times = np.array(ts.pytimes)
times = times[~ts.nodata]

values = ts.values
values = values[~ts.nodata]
```

**Comment by mylesmcm** [comment]
@gyanz This is an elegent approach using Numpy's Boolean Array Indexing. Very Cool! 

I do see one potential issue though, by removing the missing times and values, you will cause any subsequent plotting to not show the missing ordinates. Plots would interpolate between the data points instead of having a gap over the missing ordinates.

For some cases, users will want to see where data is missing in tables and plots.

**Comment by gyanz** [comment]
@mylesmcm  You can change the dss nodata to np.nan or any other value (e.g., -9999) with the 
 following. Hope this helps.
```
times = np.array(ts.pytimes)
values = ts.values
values[ts.nodata] = np.nan 
```
